#!/usr/bin/env python3
"""Generate the original Pool PCM effects outside the RV32 gameplay thread."""
import argparse
from pathlib import Path


def cdiv(value, divisor):
    return value // divisor if value >= 0 else -((-value) // divisor)


def generate():
    lines = ['/* Generated by tools/generate_sound.py. Original Pool effects, signed PCM16 at 44100 Hz. */']
    for effect, (duration, frequency) in enumerate(zip((35, 25, 30, 90, 120, 160), (420, 1100, 220, 740, 150, 880)), 1):
        frames = 44100 * duration // 1000
        samples = []
        phase, noise = 0, 0x504F4F4C
        for i in range(frames):
            hz = 1320 if effect == 6 and i > frames // 2 else frequency
            phase = (phase + hz * 65536 // 44100) & 65535
            wave = phase if phase < 32768 else 65535 - phase
            wave = cdiv(wave - 16384, 5)
            if effect <= 3:
                noise = (noise * 1664525 + 1013904223) & 0xFFFFFFFF
                wave = cdiv(wave + (noise >> 20) - 2048, 2)
            envelope = frames - 1 - i
            if i < 100:
                envelope = envelope * i // 100
            samples.append(cdiv(wave * envelope, frames))
        lines.append(f'static const int16_t effect_{effect}[] = {{')
        for i in range(0, frames, 12):
            lines.append('    ' + ', '.join(map(str, samples[i:i + 12])) + ',')
        lines.append('};')
    return '\n'.join(lines) + '\n'


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    target = Path(__file__).resolve().parents[1] / 'assets' / 'sound_pcm.inc'
    output = generate()
    if args.check:
        if target.read_text() != output:
            raise SystemExit('Pool PCM is stale; run tools/generate_sound.py')
        print('Pool PCM generation matches committed data')
    else:
        target.write_text(output)
