#!/usr/bin/env python3
"""Regenerate the Q12 quarter-wave table; no runtime floating point is used."""
import math
from pathlib import Path

values = [int(math.sin(i * math.pi / 2048) * 4096 + 0.5) for i in range(1025)]
output = '/* Generated by tools/generate_angles.py: sin(0..pi/2), Q12. */\n'
output += '\n'.join(', '.join(map(str, values[i:i + 16])) + ',' for i in range(0, len(values), 16)) + '\n'
(Path(__file__).resolve().parents[1] / 'assets' / 'sine_q12.inc').write_text(output)
