APP_NAME := tester

SOURCES := $(CURDIR)/src/main.c \
           $(CURDIR)/src/harness.c \
           $(CURDIR)/src/tests/arguments.c \
           $(CURDIR)/src/tests/stdio.c \
           $(CURDIR)/src/tests/heap.c \
           $(CURDIR)/src/tests/filesystem.c \
           $(CURDIR)/src/tests/input.c \
           $(CURDIR)/src/tests/process.c \
           $(CURDIR)/src/tests/runtime.c \
           $(CURDIR)/src/tests/graphics.c

include ../../sdk/make/application.mk
