#!/usr/bin/env python3
"""Generate the original Soccer PCM effects outside the RV32 gameplay thread."""
import argparse
from pathlib import Path


def cdiv(value, divisor):
    return value // divisor if value >= 0 else -((-value) // divisor)


def generate():
    melodies = ((330, 220), (180, 90), (390, 180), (110, 70), (550, 330),
                (1200, 880), (660, 880, 1100, 1320), (2200, 0, 2200), (1800, 0, 1800, 1500))
    lines = ['/* Generated by tools/generate_sound.py. Original Soccer PCM16 effects at 44100 Hz. */']
    for effect, melody in enumerate(melodies, 1):
        samples = []
        for frequency in melody:
            phase = 0
            for i in range(1764):
                phase = (phase + frequency * 65536 // 44100) & 65535
                wave = phase if phase < 32768 else 65535 - phase
                wave = cdiv(wave - 16384, 4) if frequency else 0
                envelope = min(i, 220, 1763 - i)
                samples.append(cdiv(wave * envelope, 220))
        lines.append(f'static const int16_t effect_{effect}[] = {{')
        for i in range(0, len(samples), 12):
            lines.append('    ' + ', '.join(map(str, samples[i:i + 12])) + ',')
        lines.append('};')
    return '\n'.join(lines) + '\n'


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    target = Path(__file__).resolve().parents[1] / 'assets' / 'sound_pcm.inc'
    output = generate()
    if args.check:
        if target.read_text() != output:
            raise SystemExit('Soccer PCM is stale; run tools/generate_sound.py')
        print('Soccer PCM generation matches committed data')
    else:
        target.write_text(output)
