if(NOT DEFINED TABOS_SOURCE_DIR)
    message(FATAL_ERROR "TABOS_SOURCE_DIR is required")
endif()

set(APP_DIRECTORIES shell tester hello_elf coreutils)
foreach(directory IN LISTS APP_DIRECTORIES)
    file(GLOB_RECURSE sources "${TABOS_SOURCE_DIR}/apps/${directory}/*.c" "${TABOS_SOURCE_DIR}/apps/${directory}/*.h")
    foreach(source IN LISTS sources)
        file(READ "${source}" contents)
        foreach(pattern IN ITEMS "api->" "tabos_runtime_api" "tabos_elf_api_t" "TABOS_ELF_API_VERSION")
            if(contents MATCHES "${pattern}")
                message(FATAL_ERROR "Application references private ELF ABI: ${source}: ${pattern}")
            endif()
        endforeach()
    endforeach()
endforeach()
