APP_NAME := files
TABOS_APP_GUI := 1
TABOS_APP_HEAP_BYTES := 4194304
TABOS_APP_STACK_BYTES := 32768
SOURCES := src/main.c
SDK_ROOT ?= ../../../sdk
PROJECT_ROOT ?= ../../..
include $(SDK_ROOT)/make/application.mk
