APP_NAME := starfall
TABOS_APP_HEAP_BYTES := 1048576
TABOS_APP_STACK_BYTES := 16384
SOURCES := src/main.c \
           src/game.c \
           src/render.c \
           src/storage.c

include ../../sdk/make/application.mk
