APP_NAME := starfall
TABOS_APP_HEAP_BYTES := 1048576
TABOS_APP_STACK_BYTES := 16384
SOURCES := $(CURDIR)/src/main.c \
           $(CURDIR)/src/game.c \
           $(CURDIR)/src/render.c \
           $(CURDIR)/src/storage.c

include ../../sdk/make/application.mk
