APP_NAME := desktop
TABOS_APP_HEAP_BYTES := 4194304
TABOS_APP_STACK_BYTES := 32768
SOURCES := src/main.c src/model.c src/render.c src/input.c

SDK_ROOT ?= ../../../sdk
PROJECT_ROOT ?= ../../..
include $(SDK_ROOT)/make/application.mk
