option(
    TABOS_ENABLE_ELF_LOADER_EXPERIMENT
    "Load and execute embedded standalone RISC-V hello ELF after boot"
    OFF
)

if(TABOS_ENABLE_ELF_LOADER_EXPERIMENT AND TABOS_ENABLE_CONSOLE_DIAGNOSTIC_APP)
    message(FATAL_ERROR
        "TABOS_ENABLE_ELF_LOADER_EXPERIMENT and TABOS_ENABLE_CONSOLE_DIAGNOSTIC_APP cannot both be enabled")
endif()
